name: Build OpenWrt Packages

on:
  schedule:
    - cron: '30 0 * * *' 
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ github.event_name == 'workflow_dispatch' || steps.check-updates.outputs.has_changes }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Check upstream changes
        id: check-updates
        if: github.event_name != 'workflow_dispatch'
        run: |
          today=$(date -u '+%Y-%m-%d')
          has_changes=false
          
          for repo in $(grep -v '^$' buildlist.txt); do
            echo "Checking $repo..."
            # 获取最新提交的日期
            latest_commit_date=$(curl -s "https://api.github.com/repos/$repo/commits?per_page=1" | jq -r '.[0].commit.committer.date[:10]')
            
            if [ "$latest_commit_date" == "$today" ]; then
              echo "Found changes in $repo on $today"
              has_changes=true
              break
            fi
          done
          
          echo "has_changes=$has_changes" >> $GITHUB_OUTPUT

      - name: Force build for manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: echo "has_changes=true" >> $GITHUB_OUTPUT

  build:
    needs: check
    if: needs.check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        branch:
          - openwrt-24.10
          - SNAPSHOT

    steps:
      - uses: actions/checkout@v4

      - name: Read build list and clone repositories
        run: |
          mkdir -p package
          while IFS= read -r repo; do
            [ -z "$repo" ] && continue
            echo "Cloning $repo..."
            git clone "https://github.com/$repo" "package/$(basename $repo)"
          done < buildlist.txt

      - name: Prepare package list
        id: pkglist
        run: |
          pkg_list=""
          while IFS= read -r repo; do
            [ -z "$repo" ] && continue
            pkg_name=$(basename $repo)
            pkg_list="$pkg_list $pkg_name"
          done < buildlist.txt
          echo "packages=${pkg_list# }" >> $GITHUB_OUTPUT
          echo "date=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: build
          PACKAGES: ${{ steps.pkglist.outputs.packages }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/build/*

      - name: Create release
        continue-on-error: true
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ steps.pkglist.outputs.date }}
          allowUpdates: true
          tag: ${{ steps.pkglist.outputs.date }}
          commit: main
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "bin/packages/${{ matrix.arch }}/build/*"

  cleanup:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Clear GitHub Actions Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh cache delete --all

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
